comment:
  layout: "header, diff, changes, sunburst"
  behavior: default
  require_changes: false  # Always post a comment even if no changes in coverage

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%    # Be strict or allow minor drops
    patch:
      default:
        target: auto
        informational: true # Don't fail the build just because patch coverage is low
