"""Add seed data for cards and users

Revision ID: 1e497156fe7c
Revises: e88ef89b8ef0
Create Date: 2025-11-01 04:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, UUID
import uuid

# revision identifiers, used by Alembic.
revision = '1e497156fe7c'
down_revision = 'e88ef89b8ef0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create table objects for bulk insert
    users_table = table('users',
        column('id', UUID),
        column('email', String),
        column('hashed_password', String)
    )

    cards_table = table('cards',
        column('id', UUID),
        column('sentence_template', String),
        column('target_word', String),
        column('hint', String),
        column('audio_url', String)
    )

    # Seed one user
    op.bulk_insert(users_table, [
        {
            'id': '00000000-0000-0000-0000-000000000000',
            'email': 'test@example.com',
            'hashed_password': 'fake_password_hash'
        }
    ])

    # Seed some cards
    op.bulk_insert(cards_table, [
        {
            'id': 'c1b1b1b1-c1b1-4b1b-8b1b-c1b1b1b1b1b1',
            'sentence_template': 'これは__ですか？',
            'target_word': '何',
            'hint': 'What',
            'audio_url': None
        },
        {
            'id': 'c2b2b2b2-c2b2-4b2b-8b2b-c2b2b2b2b2b2',
            'sentence_template': '私__猫が好きです。',
            'target_word': 'は',
            'hint': 'Topic marker',
            'audio_url': None
        },
        {
            'id': 'c3b3b3b3-c3b3-4b3b-8b3b-c3b3b3b3b3b3',
            'sentence_template': '毎朝、コーヒー__飲みます。',
            'target_word': 'を',
            'hint': 'Object marker',
            'audio_url': None
        },
        {
            'id': 'c4b4b4b4-c4b4-4b4b-8b4b-c4b4b4b4b4b4',
            'sentence_template': 'あそこ__銀行があります。',
            'target_word': 'に',
            'hint': 'Location marker',
            'audio_url': None
        },
        {
            'id': 'c5b5b5b5-c5b5-4b5b-8b5b-c5b5b5b5b5b5',
            'sentence_template': '週末__何をしますか？',
            'target_word': 'は',
            'hint': 'Topic marker',
            'audio_url': None
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: A more robust downgrade would be selective, but for seed data, deleting is fine.
    op.execute("DELETE FROM cards")
    op.execute("DELETE FROM users WHERE id = '00000000-0000-0000-0000-000000000000'")
    # ### end Alembic commands ###
