"""Add deck settings

Revision ID: 5b8d56f348f0
Revises: 57bef366bbb5
Create Date: 2025-12-30 12:40:35.238101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8d56f348f0'
down_revision: Union[str, Sequence[str], None] = '57bef366bbb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_deck_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'active_deck_ids')
    # ### end Alembic commands ###
