"""Add deck metadata

Revision ID: 9b4c214ac860
Revises: 5b8d56f348f0
Create Date: 2025-12-30 13:05:25.164601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4c214ac860'
down_revision: Union[str, Sequence[str], None] = '5b8d56f348f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('difficulty', sa.String(), nullable=True))
    op.add_column('decks', sa.Column('tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'tags')
    op.drop_column('decks', 'difficulty')
    # ### end Alembic commands ###
