"""add srs fields to user card association

Revision ID: c48103ddeb17
Revises: 0f56efae7d2b
Create Date: 2025-11-16 15:30:01.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c48103ddeb17'
down_revision = '0f56efae7d2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_card_associations', sa.Column('interval', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user_card_associations', sa
.Column('ease_factor', sa.Float(), nullable=False, server_default='2.5'))
    op.add_column('user_card_associations', sa.Column('lapses', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('user_card_associations', 'next_review_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_card_associations', 'next_review_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('user_card_associations', 'lapses')
    op.drop_column('user_card_associations', 'ease_factor')
    op.drop_column('user_card_associations', 'interval')
    # ### end Alembic commands ###