"""Add nullable guid to card model

Revision ID: d8fba10e8363
Revises: 9bfa2422445f
Create Date: 2025-11-07 23:08:06.701717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fba10e8363'
down_revision: Union[str, Sequence[str], None] = '9bfa2422445f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('guid', sa.String(), nullable=True))
    op.create_index(op.f('ix_cards_guid'), 'cards', ['guid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_guid'), table_name='cards')
    op.drop_column('cards', 'guid')
    # ### end Alembic commands ###
