name: Backend CI

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Or your desired python version

      - name: Install Dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run Database Migrations
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          cd backend
          alembic upgrade head

      - name: Run Tests
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          PYTHONPATH=backend/ pytest backend/tests/

      - name: Check for DB Model Changes
        env:
          DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
        run: |
          cd backend
          alembic check
